### PR TITLE
Change all arrays of numbers to ReadonlyArrays

### PR DESCRIPTION
**Pull request by devin2712**
These arrays are not modified at runtime, so they could just be ReadonlyArrays.

### CODE REVIEW

**Comment by sghall** [comment]
Thanks for the PR!  Yeah, this is kind of interesting.  I don't use Typescript at work, but I'm starting to adopt this for my own projects. Some of the finer points escape me.  

First, I think the domain,  values returned from mode, and the values prop should definitely be read only. 

I'm sending the user a new array in the handlers so I don't care if they mutate it.  I'm, as a matter of principle, opposed to most mutations but would it be correct to impose that on the user?

Thoughts?

**Comment by astorije** [comment]
@sghall, by accepting `ReadonlyArray<T>` instead of `Array<T>` in props, you don't impose this on the user/consumer, rather you express that you promise not making changes to the passed arrays.

In practice, this means that if a prop is a `ReadonlyArray<T>` (@devin2712's PR), a consumer can pass it a `ReadonlyArray<T>` or a `Array<T>` interchangeably (if the latter, fine, you give me a mutable array, but I am not going to mutate it). If the prop is an `Array<T>` (current code), then consumers cannot pass a `ReadonlyArray<T>` because you are requesting an array that supports mutations.
This is the situation we are hitting that this PR is fixing: we only have `ReadonlyArray<number>` floating around, but when passing it to the slider, we have to actively cast them with `as number[]`.

So @devin2712's changes actually make the API more flexible while being more accurate on what it does. In fact, I have done [a very similar change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25487) to `@types/node`.

**Comment by sghall** [comment]
Hey, @astorije thanks for adding some more color on this!  Good stuff.  Makes sense now.

**Comment by astorije** [comment]
Awesome @sghall, thanks! Are you planning on making a release? 🙏

**Comment by sghall** [comment]
Ok.  Just released this. Thanks again!  Would appreciate any other help getting the types dialed in if you encounter problems ;)  

https://github.com/sghall/react-compound-slider/releases/tag/v0.15.0

**Pull request merged**
