### PR TITLE
Tooltips, AutoSnap & Grabbing handle after rail click

### PR DESCRIPTION
**Pull request by thunderkid**
Hi. This PR implements the three features we discussed:

1) Handle position values are now automatically rounded to the appropriate step, rather than generating a warning if they don't match. This feature is on by default, but can be turned off with the `noAutoSnap` property. There's also a `noWarnOnSnap` flag provided. (I can't see any uses beyond the default behavior now, but the flags are there just in case. I didn't end up exposing the rounding function since the default system now seems robust enough.
I've tested the feature on my own projects that previously had rounding issues due to non-nice step-sizes and it works well. The RCS demo pages all have polite step values so didn't exhibit rounding problems anyhow.

2) `MouseDown` on a track or rail now immediately 'grabs' the handle that moves to the click point. However, if a handle can't reach that point due to the mode constraints, then nothing is grabbed. This works well on all sliders in the demo pages.

3) `<Tooltip>`'s are implemented following the same child component paradigm as `<Rail>`, `<Handle>`, etc, and should be fully flexible. I've added an example with tooltips to each of the demo pages - horizontal, vertical, and materialUi (though I didn't do any material styling on that one...)
Tooltips exhibit different styles depending on whether the pointer is hovering over the rail/track, or hovering over a handle. While a handle is sliding, the tooltip is attached to that handle regardless of pointer position. Only this last tooltip type applies for touch events.

To implement these, I did a fair bit of refactoring:

- Mouse events over the rail/track/handle system (the 'gadget') are now passed back to `Slider` to be handled by `onMouseEnterGadget` etc.

- Properties of `Slider` (eg `this.active`) have been moved into `state` - I needed this to provide the flexibility for styling tooltips and later I think it will more cleanly allow `<Handle>`'s to be styled differently if they're active.

- There were some DRY opportunities in `Slider.js`, for example the further unification of touch/mouse handling.

- The `setState` logic has been rearranged. I needed it to be more functional, especially for the issue of grabbing handles after a rail click. I went through a couple of iterations to sort out some `setState` async issues but I think it's now pretty clean.

- A couple of tweaks to the build system were needed for windows - won't work off windows though.

Other than that I've tried to maintain the current style. All unit tests are passing, though I didn't add any more. Performance seems fine, though I didn't benchmark it carefully. Touch events have only been tested in the Chrome simulator, but they seem ok there.

Cheers.

### CODE REVIEW

**Comment by sghall** [comment]
I really appreciate the PR.   There's a lot of good stuff in here but this PR is massive.  I'm wondering if you want to step through these features and put each one in a separate, focused PR.  As is, I cannot merge this.   I think the biggest issue is the slider now renders on every mouse move even if you don't have tooltips implemented.

**Comment by thunderkid** [comment]
Yes, it got quite involved. Sorry!

In terms of the rerender on each mouse move you're right. I've just added to the PR a quick test `usingTooltips()` so that the hover logic won't be applied if you don't have a `<Tooltip>` included. I believe now that rendering of tooltipless sliders should be no less efficient than it was before. I should have included this with yesterday's PR, but it actually touches on a broader performance issue that I was going to look at more closely. For example, `<Rail>` and `<Ticks>` have always been rendered on every mouse move while a handle is grabbed, and this is generally unnecessary.

**Comment by sghall** [comment]
Ok.  Yeah,  I think maybe you're just digging yourself in further on the tooltips.  I don't think the slider should care at all if someone wants to render tooltips.  I think we can deal with that by just passing down a function.  If you want tooltips on the rail (or tracks) you can just do that.  All you need to know is what the value is at some x or y value.  For tooltips on the handle, you have that already.  You know what the value is. if you want to show a tooltip go ahead.  Probably just need to add an example.

The good news is you now know the whole codebase really well and have all the pieces to handle all these PRs.  **You want to just tee up a very small PR that just deals with optional warning on changing values and snapping to values?**  I saw what you did but I have some questions on this.  Would be much easier to just focus in on that one piece and get it merged.

Let's just use this as a master list and see what we can do for each of these issues.

**Comment by thunderkid** [comment]
In terms of separating out the PR:

1) The snap logic is pretty isolated, and could be done easily.
2) Grabbing after a click was surprisingly involved, and required sorting out the setState logic quite carefully. Separating this part from (4) would be a fair bit of work, would be error-prone at this point, and would still represent a lot of changes in `Slider`.
3) The tooltip logic also required a lot of changes in `Slider` as well as the new event flow between `Slider` and the child components. Separating it from (2) and (4) would be hard.
4) I suppose some general tidying of `Slider` and DRY unification of mouse/touch could have been done in absence of (2) and (3). But unless it was in order to implement something like (2) I'm not sure it would be worth the bother.

So 2,3,4 are very intertwined and trying to isolate any of them at this point would consist of a fair bit of painstaking cutting and pasting. If they were all then going to be applied sequentially to your `master`, then that would - assuming zero mistakes - end up with the exact same result for a lot more work. Did you want them separated so it's easier for you to check the logic of the changes, or are you thinking that you might want to merge some of these features, but not all?

**Comment by thunderkid** [comment]
Sorry - didn't see your last comment before I sent mine.

**Pull request closed without merging**
